name: Merge PDFs from Drive (por carpeta, a 'Compilados')

on:
  schedule:
    # GitHub Actions corre en UTC.
    # 11:00 UTC = 06:00 a. m. Bogotá (UTC-5), todos los lunes
    - cron: "0 11 * * 1"
  workflow_dispatch: {}  # deja esto para poder ejecutarlo manualmente
jobs:
  merge:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run merge
        env:
          AUTH_MODE: oauth
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          FOLDER_IDS: ${{ secrets.FOLDER_IDS }}                  # ["id1","id2",...]
          MIN_PDFS: "1"                                          # Cambia si quieres
          DRY_RUN: "false"                                       # Pon "true" para pruebas
          COMPILED_SUBFOLDER_NAME: "Compilados"                  # Puedes renombrarla si quieres
        run: |
          python src/merge_pdfs.py
